version: '3'
services: 
    database:
        image: 'mongo'
        container_name: 'mongodb-botanalyzer'
        environment: 
            - MONGO_INITDB_DATABASE=bot_analyzer
        volumes: 
            - ./mongo-volume:/data/db
        ports: 
            - '27017-27019:27017-27019'