on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'
name: Create Release

jobs:

  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script - Dashboard
        run: sh build/build_dashboard_adminator.sh

      - name: Run build script - Dashboard API
        run: sh build/build_dashboard_api.sh

      - name: Run build script - NLP API
        run: sh build/build_nlp_api.sh

      - name: Build release package
        run: sh build/build_release.sh ${{ github.ref }}

      - uses: actions/upload-artifact@v2
        with:
          name: dashboard_api_artifact
          path: target/*.tar.gz
  
      - name: Upload release artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true