on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'
name: Create Release

jobs:

  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script - Dashboard
        run: sh build_dashboard_adminator.sh

      - name: Run build script - Dashboard API
        run: sh build_dashboard_api.sh

      - name: Run build script - NLP API
        run: sh build_dashboard_api.sh

      - name: Build release package
        run: sh build_release.sh GITHUB_REF
        
      - name: Create Release
        id: create_release 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - uses: actions/upload-artifact@v2
        with:
          name: dashboard_api_artifact
          path: target/*.tar.gz
  
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip